Docs: added english clever-show docs
CopterExpress/clover pull request #274
Opened 2020-09-27 00:36 UTC by artem30801

2020-09-27 14:37 UTC, okalachev commented
There is a lot of repeating errors: incorrect links, broken images, etc. Too many issues to check the whole PR.

Also markdown-lint find tons <sup>[1](https://travis-ci.org/github/CopterExpress/clover/jobs/730606843#L935) [2](https://travis-ci.org/github/CopterExpress/clover/jobs/730606843#L2633)</sup> of issues.

Don't you want to keep the whole documentation in the `clever-show`'s repository and only have basic article in here?

2020-09-27 14:38 UTC, okalachev requested changes
There is a lot of repeating errors: incorrect links, broken images, etc. Too many issues to check the whole PR.

Also markdown-lint find tons <sup>[1](https://travis-ci.org/github/CopterExpress/clover/jobs/730606843#L935) [2](https://travis-ci.org/github/CopterExpress/clover/jobs/730606843#L2633)</sup> of issues.

Don't you want to keep the whole documentation in the `clever-show`'s repository and only have basic article in here?

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show.md
> +* Arthur Golubtsov, ex-software engineer in COEX, https://github.com/goldarte
Не думаю, что это уточнение обязательно, зачем?

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/animation.md
> +f the copter takes off from the ground in the animation file, at the start of the animation, the instantaneous playback logic (fly)** will be applied: the copter with the motors turned off plays the
f?

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/animation.md
> +Create object animations in [Blender](https://www.blender.org) or use [examples](.../../examples/animations).
This link seems to lead nowhere.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/animation.md
> +* Blender distance units are converted into meters
Точка

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/animation.md
> +If you need information about which points the copter will fly to as a result of loading the animation on the current client parameters, use the [animation_info](../../tools/animation_info.py) utilit
This link leads nowhere.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/blender-addon.md
> +* Open Blender, select `Edit > Preferences` from the top menu. In the opened settings window, select `Add-ons` in the side panel. Click the button `Install...` in the upper right corner of the window
Пункты меню и прочее лучше выделять, например, курсивом. "`" - для символов (названия переменных, функций, файлов и т. д.).

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/blender-addon.md
> +* `Use name filter for objects` - checkbox determines if the object filter will be used while saving the paths. If this option is disabled, the paths of all visible objects will be exported.`Name ide
Русский текст.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/blender-addon.md
> +* `Documentation` - leads to the addon's documentation page
Очень много пунктов списков без точки.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/client.md
> +The client is the `clever-show` service in the copter operating system. The service runs the [client.py](.../.../drone/client.py) script and starts automatically when the operating system boots. If i
Неправильный символ, закрывающий `.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/animation.md
> +2. Copter takes off - `takeoff'.
Неправильный символ, закрывающий `.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/client.md
> +The ''failsafe'' service is designed for automatic landing of the copter in emergency situations:
Что за '' синтаксис?

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/client.md
> +Also `failsafe` provides '`/emergency_land` ROS service, which can be accessed by the client upon command from the server for emergency drone landing.
Лишний '

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/client.md
> +Logs of both services are written to the`/var/log/syslog` file of the drone's on-board computer Raspberry Pi  operating system. The log files of the current session are available for viewing upon exe
Не хватает пробела после the.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/client.md
> +**Warning!** Rotations `roll`, `pitch`, `yaw` are made sequentially in the stated order.
Do you want to make a box?

Then correct syntax is:

```markdown
> **Warning** Text
```

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/client.md
> +2. Copter takes off - `takeoff'.
Неверный закрывающий символ.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/client.md
> +
There should not be extra line breaks between list items.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/client.md
> +Settings of the LED strip use on the copter. To configure the LED strip itself, you need to configure the `led.launch` file, see [LED strip in Clover](https://clover.coex.tech/ru/leds.html) for detai
Don't use Clover documentation full URL. Just `leds.md`. Also, why `ru`?

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/client.md
> +* `thrust` - the initial power supplied to the motors in the event of a `emergency_land` action when the emergency protection is triggered. Measurementless value, from 0 (no thrust) to 1 (full thrust
Incorrect warning box syntax.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/client.md
> +* `thrust` - the initial power supplied to the motors in the event of a `emergency_land` action when the emergency protection is triggered. Measurementless value, from 0 (no thrust) to 1 (full thrust
PX4 is uppercase.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/client.md
> +* `use_ntp` - determines whether time synchronization using NTP will be used. (if `False', the local OS time will be used (synchronized automatically when using chrony). * It is recommended to use ch
Incorrect ` symbol pair.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/client.md
> +* `use_ntp` - determines whether time synchronization using NTP will be used. (if `False', the local OS time will be used (synchronized automatically when using chrony). * It is recommended to use ch
There should not be a space between "*" and the text.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/image-building.md
> +* Place the Clover configuration folders (`launch`, `map` and `camera_info`) in the`builder/clever-config`  [folder](../../builder/clever-config)  in the clever-show source directory.
Link to nowhere.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/image-building.md
> +* Place the Clover configuration folders (`launch`, `map` and `camera_info`) in the`builder/clever-config`  [folder](../../builder/clever-config)  in the clever-show source directory.
Space lacking.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/image-building.md
> +  * All files from the `launch` folder will be copied to the `/home/pi/catkin_ws/src/clever/clever/launch' directory in the built image.
Incorrect ` pair.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/image-building.md
> +where `<MOVE_FILE>` is the file to be moved to the image (location relative to the folder with the image, for example `.../builder/assets/clever-show.service`) and `<MOVE_TO>` is the path in the imag
Link to nowhere.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +The `clover` software officially supports the following [positioning systems](https://clover.coex.tech/en/programming.html#positioning) :
Extra space.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +The `clover` software officially supports the following [positioning systems](https://clover.coex.tech/en/programming.html#positioning) :
Don't use full documentation URL.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +* [optical flow](https://clover.coex.tech/en/optical_flow.html)
Ending dots in the list.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +* [optical flow](https://clover.coex.tech/en/optical_flow.html)
Don't use full URL.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +**Following configuration examples are for the Clover 4 copter, assembled and configured according to the [documentation](https://clover.coex.tech)**.
Rich quote is better here.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +**Following configuration examples are for the Clover 4 copter, assembled and configured according to the [documentation](https://clover.coex.tech)**.
Provide a full link + without domain.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +* [Calibrating camera](https://clover.coex.tech/en/camera_calibration.html).
Don't use full URLs.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +Make sure that the copter holds the position autonomously: mark the checkbox near the name of the copter and press the "Takeoff" button in the right panel of the server interface. The copter should t
Link to nowhere.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +Make sure that the copter holds the position autonomously: mark the checkbox near the name of the copter and press the "Takeoff" button in the right panel of the server interface. The copter should t
Rich quote is better here.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +* The flight controller configuration file can be saved by connecting to the flight controller through [QGroundControl](http://qgroundcontrol.com) application. It is possible to connect directly to t
Use relative URL.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +* * The camera calibration file is useful for refinement of visual positioning. The name of the calibration file should consist of the id of the copter, for which the calibration was made, with the a
User relative URL. Why `ru`?

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +* * The camera calibration file is useful for refinement of visual positioning. The name of the calibration file should consist of the id of the copter, for which the calibration was made, with the a
Wrong ` pair.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +The `clever-show' software suite includes many status checks of the copters to minimize the number of failed launches as well as a set of parameters to configure the positioning systems. All settings
Wrong ` pair.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +All the configuration files for `optical flow` configuration are located in the  [examples/positioning/optical flow](../../examples/positioning/optical flow/) folder.
Link to nowhere.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +An example of a `.launch` configuration file: [clover.launch](../../examples/positioning/optical flow/launch/clover.launch).
=== " ===

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/positioning.md
> +Server configuration with values applicable to work with `optical flow`: [server.ini](../../examples/positioning/optical%20flow/server.ini).
A lot of links to nowhere.

2020-09-27 14:38 UTC, okalachev commented on docs/en/clever-show/server.md
> +  ![Скриншот раздела Server - music](../assets/server-music.png)
No Russian letters in file names.

2020-09-28 00:27 UTC, artem30801 commented on docs/en/clever-show.md
> +* Arthur Golubtsov, ex-software engineer in COEX, https://github.com/goldarte
Артур ушёл, и по сути я сейчас занимаюсь поддержкой и сопровождением, так что лучше уж меня дергают если будут дёргать

2020-09-28 00:30 UTC, artem30801 commented
Спасибо большое за замечания, прошёлся по ним - надеюсь, ничего не упустил. Загрузил картинки-ассеты и пофиксил все (я надеюсь x2) ссылки.

2020-09-28 12:25 UTC, artem30801 commented
markdownlint ругается на строковые значения (элементы конфигов) и слова (например windows) в нарицательном контексте

2020-09-29 22:04 UTC, okalachev commented
Ок, посмотрю подробнее в ближайшие несколько дней.

2020-10-02 16:49 UTC, okalachev commented
Мы не можем добавлять 4-х мегабайтные гифки в репозиторий: каждый файл попадает в образ Клевера и удалить его из истории гита невозможно.

Большие изображения нужно либо уменьшать, либо убирать.

2020-10-07 15:30 UTC, closed without merging