docs: Assembling grips and fpv
CopterExpress/clover pull request #283
Opened 2020-10-23 14:04 UTC by Alamoris

2020-10-27 12:44 UTC, okalachev commented
Links from other related articles needed.

2020-10-27 12:46 UTC, okalachev requested changes

2020-10-27 12:46 UTC, okalachev commented on docs/ru/magnetic_grip.md
> +<img src="../assets/magnet_grip/scheme.jpg" width=300 class="zoom border center">
File is missing.

2020-10-27 12:46 UTC, okalachev commented on docs/ru/magnetic_grip.md
> +    <img src="../assets/magnet_grip/magnet2.png" width=300 class="zoom border center">
Here and further: files are missing.

2020-10-27 12:51 UTC, okalachev commented on docs/ru/magnetic_grip.md
> +<img src="../assets/magnet_grip/magnet_adruino1.png" width=300 class="zoom border center">
Note: the file should spell arduino, not "adruino1".

2020-10-27 12:51 UTC, okalachev requested changes

2020-10-27 12:51 UTC, okalachev commented on docs/ru/magnetic_grip.md
> +<img src="../assets/magnet_grip/magnet_adruino1.png" width=300 class="zoom border center">
Note: the files should spell arduino, not "adruino1".

2020-11-12 13:28 UTC, Alamoris commented
Added images and fixed naming errors

2020-11-20 12:12 UTC, okalachev commented
@Alamoris, add links to these articles from whatever assembly-related articles, when they are needed.

2020-11-20 12:12 UTC, merged