docs: add COEX Duocam russian docs
CopterExpress/clover pull request #285
Opened 2020-11-02 19:11 UTC by kpetrykin

This is a short how-to about using Duocam camera

2020-11-02 19:50 UTC, okalachev requested changes
`gitup_seek.png` is too large. Change the resolution or/and use JPG.

2020-11-02 19:50 UTC, okalachev commented on docs/ru/duocam.md
> +[Подробнее об архитектуре DuoCam и программе duocam-mavlink](duocam_mavlink.md).
Broken link.

2020-11-02 20:09 UTC, kpetrykin reviewed
It looks like I need to install russian spellchecker

2020-11-03 13:32 UTC, okalachev requested changes
https://travis-ci.org/github/CopterExpress/clover/jobs/740962993#L935.

Also, `duocam_mavlink.md` is not added to summary.

2020-11-07 19:05 UTC, kpetrykin commented
I don't think we need a direct link to duocam-mavlink article here because it is conceptually a part of COEX Duocam article.

As for linter, it fails on "duocam-mavlink" string which is a name of uttility and writing it as "duocam-MAVLink" would be wrong.

2020-11-07 22:50 UTC, okalachev commented
Any article should be in the summary to be accessible. That's how gitbook works.

Symbols (like a utility binary name) should be places into ` symbols, this way they would be linted by markdown-lint. Or you can suppress this lint using `<!-- markdownlint-disable XXXXX -->` syntax.

Documents that don't pass the tests cannot be merged.

2020-11-16 10:29 UTC, merged