Drone-Agronom
CopterExpress/clover pull request #308
Opened 2021-03-15 06:27 UTC by slavikyd

2021-03-16 14:54 UTC, okalachev commented
Is this a draft or a full article?

2021-03-16 15:12 UTC, okalachev requested changes

2021-03-16 15:12 UTC, okalachev commented on docs/ru/SUMMARY.md
> -
You don't have to remove this line.

2021-03-16 15:12 UTC, okalachev commented on docs/ru/drone-agronom.md
> +Дрон-Агроном
Formatting is lacking.

Also, I suggest you to add some images, YouTube videos, etc...

2021-03-16 20:10 UTC, slavikyd commented on docs/ru/drone-agronom.md
> +Дрон-Агроном
хорошо мы сделаем, просто пока их нету...

2021-03-16 20:13 UTC, slavikyd commented on docs/ru/drone-agronom.md
> +Дрон-Агроном
а как делать форматирование?

2021-03-16 20:15 UTC, slavikyd commented
> Is this a draft or the full article?

Да это драфт. Полностью сделать не успеваю т.к я сейчас на ДПП...

2021-03-16 20:16 UTC, okalachev commented on docs/ru/drone-agronom.md
> +Дрон-Агроном
Смотрите другие статьи.

2021-03-16 20:19 UTC, slavikyd commented on docs/ru/drone-agronom.md
> +Дрон-Агроном
Хорошо

2021-03-16 20:53 UTC, slavikyd commented on docs/ru/SUMMARY.md
> -
Уже исправил.

2021-03-18 13:07 UTC, merged

2021-03-18 13:08 UTC, okalachev commented
I edited a little and merged your article as is for now.

You can continue working and send updates as other PR tomorrow and later. Also, please, give me some your contacts (e-mail, Telegram, ...), I will add them to the article too.