Hardaton quidditch
CopterExpress/clover pull request #315
Opened 2021-03-17 15:57 UTC by Ivan-Alekov

2021-03-18 14:04 UTC, okalachev commented
Please, provide the main contact for the article (e-mail, Telegram, ...), so I'll put it into the article.

2021-03-18 14:42 UTC, okalachev requested changes
I edited your article. Please, resolve the issues I mentioned.

2021-03-18 14:42 UTC, okalachev commented on docs/ru/hardaton_quidditch.md
> +![Название проекта](https://github.com/Ivan-Alekov/clover/blob/Hardaton_Quidditch/docs/assets/Hardaton_Quidditch/Hardaton.jpg)
External images are not allowed. Please, commit them to the repo.

(See in other articles how to embed them).

2021-03-18 14:42 UTC, okalachev commented on docs/ru/hardaton_quidditch.md
> +![Картинка 1](https://github.com/Ivan-Alekov/clover/blob/Hardaton_Quidditch/docs/assets/Hardaton_Quidditch/1.jpg)
Please, commit the images.

2021-03-18 14:42 UTC, okalachev commented on docs/ru/hardaton_quidditch.md
> +[Видео](https://disk.yandex.ru/d/6kNI1smfWhWYXA?w=1) о команде и с полётной зоны
Can you please put the videos to YouTube and embed them directly to the article?

2021-03-18 17:40 UTC, Ivan-Alekov commented on docs/ru/hardaton_quidditch.md
> +[Видео](https://disk.yandex.ru/d/6kNI1smfWhWYXA?w=1) о команде и с полётной зоны
Это нормально что видео через iframe в git не отображается?

2021-03-18 17:41 UTC, okalachev commented on docs/ru/hardaton_quidditch.md
> +< iframe  width = " 560 " height = " 315 " src = " https://www.youtube.com/embed/HdHbZFz7nR0 " frameborder = " 0 " allow = " акселерометр; autoplay; encrypted-media; gyroscope; picture-in -Picture "
What are these spaces for? And "акселерометр" in Russian?

2021-03-18 17:41 UTC, okalachev commented on docs/ru/hardaton_quidditch.md
> +[Видео](https://disk.yandex.ru/d/6kNI1smfWhWYXA?w=1) о команде и с полётной зоны
Да, оно будет отображаться на clover.coex.tech.

2021-03-18 17:42 UTC, Ivan-Alekov commented on docs/ru/hardaton_quidditch.md
> +< iframe  width = " 560 " height = " 315 " src = " https://www.youtube.com/embed/HdHbZFz7nR0 " frameborder = " 0 " allow = " акселерометр; autoplay; encrypted-media; gyroscope; picture-in -Picture "
Все было на англ, откуда русский не знаю
<iframe width="1280" height="720" src="https://www.youtube.com/embed/6R4tLkZVmcs" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

2021-03-19 11:26 UTC, merged

2021-03-19 11:28 UTC, okalachev commented
@Ivan-Alekov, I merged your article, but there is two issues:

1. Please, provide me your contact info (e-mail/Telegram/...) that can be put in the header of the article.
2. Please, store all the materials (documents, video) on GitHub or YouTube, instead of Yandex.Disk. Yandex.Disk in unreliable place for external linking.

2021-03-19 14:21 UTC, Ivan-Alekov commented
1)
onlyfor-works@yandex.ru
@ivan_alekov - Telegram
2)Пожалуйста, храните все материалы (документы, видео) на GitHub или YouTube, а не на Яндекс.Диске. Яндекс.Диск в ненадежном месте для внешних ссылок.
Мне надо все перенести?