add files for 3d print from article #338
CopterExpress/clover pull request #339
Opened 2021-06-04 19:42 UTC by 1Den4ik1

add files for 3d print from article #338

2021-06-05 07:56 UTC, okalachev requested changes

2021-06-05 07:56 UTC, okalachev commented on docs/ru/models.md
> +* **Груз для магнитного захвата** - [Gruz_dlya_magnitnogo_zahvata](docs/assets/dxf/Gruz_dlya_magnitnogo_zahvata.stl)
Отсутствуют файлы, на которые ты ссылаешься. И называть их надо по-английски.

2021-06-05 20:56 UTC, 1Den4ik1 commented on docs/ru/models.md
> +* **Груз для магнитного захвата** - [Gruz_dlya_magnitnogo_zahvata](docs/assets/dxf/Gruz_dlya_magnitnogo_zahvata.stl)
я их залил в папку докс ассетс, dxf, вчера были, сеня исчезли. где-то ошибся? ща снова залью, ок? называть по английски всмысле не транслитом а словами английскими?

2021-06-05 20:58 UTC, 1Den4ik1 commented on docs/ru/models.md
> +* **Груз для магнитного захвата** - [Gruz_dlya_magnitnogo_zahvata](docs/assets/dxf/Gruz_dlya_magnitnogo_zahvata.stl)
![image](https://user-images.githubusercontent.com/84790613/120905300-de5da480-c659-11eb-9e1b-998651e6cc81.png)
вот, они тут были, подскажи, что не так сделал пжлст

2021-06-07 11:27 UTC, okalachev commented on docs/ru/models.md
> +* **Груз для магнитного захвата** - [Gruz_dlya_magnitnogo_zahvata](docs/assets/dxf/Gruz_dlya_magnitnogo_zahvata.stl)
Наверное, ты их закоммитил в какую-то другую ветку.

2021-06-08 09:53 UTC, 1Den4ik1 commented on docs/ru/models.md
> +* **Груз для магнитного захвата** - [Gruz_dlya_magnitnogo_zahvata](docs/assets/dxf/Gruz_dlya_magnitnogo_zahvata.stl)
я не сделал пул реквест сцудя по всему, поэтому файлы не залились. А теперь должны быть, посмотри пжлст.

2021-06-08 12:55 UTC, 1Den4ik1 commented on docs/ru/models.md
> +* **Груз для магнитного захвата** - [Gruz_dlya_magnitnogo_zahvata](docs/assets/dxf/Gruz_dlya_magnitnogo_zahvata.stl)
#346 тут

2021-06-14 09:50 UTC, 1Den4ik1 commented on docs/ru/models.md
> +* **Груз для магнитного захвата** - [Gruz_dlya_magnitnogo_zahvata](docs/assets/dxf/Gruz_dlya_magnitnogo_zahvata.stl)
look, files name and address have been changed

2021-06-14 09:58 UTC, 1Den4ik1 commented
https://github.com/CopterExpress/clover/pull/346#issue-664611768

2021-06-14 09:59 UTC, 1Den4ik1 reviewed
Change name files

2021-06-14 09:59 UTC, 1Den4ik1 reviewed
change files name

2021-06-17 18:07 UTC, closed without merging