copterhack2022 - Drone observe autonomous car - Dragon&Tanker
CopterExpress/clover pull request #388
Opened 2021-09-15 06:46 UTC by uml4

2021-09-15 12:08 UTC, okalachev requested changes
Hi! Please, check my suggestions and markdownlint's output: https://github.com/CopterExpress/clover/pull/388/checks?check_run_id=3609738409#step:5:4.

Shouldn't the article file be named drone_observe**s**_autonomous_car.md? Or you can name your article your team's name, for simplicity (but without capital letters and special characters).

2021-09-15 12:08 UTC, okalachev commented on docs/en/drone_observe_autonomous_car.md
> +(Describe the team: full name, contacts (e-mail/Telegram username), role in the team).
```suggestion
```

2021-09-15 12:08 UTC, okalachev commented on docs/en/drone_observe_autonomous_car.md
> +
```suggestion
```

2021-09-15 12:08 UTC, okalachev commented on docs/en/drone_observe_autonomous_car.md
> +<img src="../assets/Dragon&Tanker.png" >
Please, don't use capital letters and special characters in file names.

2021-09-15 14:26 UTC, uml4 commented
Thank you for your review. I have update the file  name and the markdown

2021-09-16 14:03 UTC, okalachev commented
Please no capital letters and special characters in file names, and please check this: https://github.com/CopterExpress/clover/pull/388/checks?check_run_id=3618929536#step:5:4.

2021-09-16 17:12 UTC, okalachev commented
I fixed some issues to comply with application requirements.

2021-09-16 18:56 UTC, SeliverstovaE commented
Dear friend,

Thank you for your interest in the CopterHack 2022 contest. Your application has successfully passed the experts’ review and was accepted for the second project stage of the competition, which will be held until February 28, 2022. This stage will be followed by monthly updates, lectures, and guidance from industry experts.

What's next?

1. Join the Telegram group with participants of the second project stage “[CopterHack 2022, participants chat](https://t.me/joinchat/1KIDu8p5FGhlYTBi )”.  
2. Every month, you're expected to prepare free-form reports on the progress of your project (update) in this draft pull request. In your report please indicate your progress, what tasks have been solved. You are encouraged to attach photos and videos that demonstrate the results of the work done within the month.
3. Send the link to the update to the participants chat in the Telegram group.

In response to the message, you will receive feedback from the competition jury.

There is no specific date for sending the report, so you can send the report between the beginning and the end of the month.

Monthly updates become mandatory from November 2021. But as soon as you are in the telegram group, you can already send updates and receive feedback from the jury.

We are interested in helping you to complete your project as much as possible by the final stage. We wish you success!

Always in touch! Your CopterHack team.

2022-04-25 07:29 UTC, closed without merging

2022-04-25 07:42 UTC, SeliverstovaE commented
Dear Dragon&Tanker team,
We are closing pull request for your project as you didn’t get to the final round of the competition. 

You are welcome to submit your article to the clover documentation as an clover platform-based project. In order to do this please create a new pull request or make a comment to the existing one.

We wish you success in implementing your project and invite you to the next events.