CopterHack-2022 CopterCat
CopterExpress/clover pull request #403
Opened 2021-10-30 16:54 UTC by matveylapin

2021-10-31 08:20 UTC, okalachev requested changes
Markdown document name should be the name of your team or your project, in English, without spaces.

2021-10-31 08:20 UTC, okalachev commented on docs/ru/FMUv6U с поддержкой распределённой сети.md
> +
```suggestion
```

2021-10-31 08:20 UTC, okalachev commented on docs/ru/FMUv6U с поддержкой распределённой сети.md
> +# Название проекта
Title should have the name of the project or the team.

2021-10-31 08:20 UTC, okalachev commented on docs/ru/FMUv6U с поддержкой распределённой сети.md
> +Полётник на stm32h7 с местом для RPI CM4 и встроенной esp32 для создания распределённой сети.
```suggestion
Полётник на stm32h7 с местом для RPi CM4 и встроенной ESP32 для создания распределённой сети.
```

2021-10-31 08:20 UTC, okalachev commented on docs/ru/FMUv6U с поддержкой распределённой сети.md
> +Плата полётного контроллера FMUv6U и api для взаимодествия с распределённой сетью через RPI
```suggestion
Плата полётного контроллера FMUv6U и API для взаимодествия с распределённой сетью через RPi.
```

2021-10-31 08:20 UTC, okalachev commented on docs/ru/FMUv6U с поддержкой распределённой сети.md
> +* Лапин Матвей @matveylapin, инеженер/программист.
`@matveylapin` won't be a link to anything, you may change it to links to `t.me` or something.

2021-10-31 12:25 UTC, matveylapin commented
Changed file name and added link to telegram

2021-11-01 12:18 UTC, okalachev commented
Sorry, only lowercase letter are allowed as some of file systems are case insensitive, which can lead to confusion. Renamed your file.

2021-11-01 13:02 UTC, SeliverstovaE commented
Dear friend,

Thank you for your interest in the CopterHack 2022 contest. Your application has successfully passed the experts’ review and was accepted for the second project stage of the competition, which will be held until February 28, 2022. This stage will be followed by monthly updates, lectures, and guidance from industry experts.

What's next?

1. Join the Telegram group with participants of the second project stage “[CopterHack 2022, participants chat](https://t.me/joinchat/1KIDu8p5FGhlYTBi )”.  
2. Every month, you're expected to prepare free-form reports on the progress of your project (update) in this draft pull request. In your report please indicate your progress, what tasks have been solved. You are encouraged to attach photos and videos that demonstrate the results of the work done within the month.
3. Send the link to the update to the participants chat in the Telegram group.

In response to the message, you will receive feedback from the competition jury.

There is no specific date for sending the report, so you can send the report between the beginning and the end of the month.

Monthly updates become mandatory from November 2021. But as soon as you are in the telegram group, you can already send updates and receive feedback from the jury.

We are interested in helping you to complete your project as much as possible by the final stage. We wish you success!

Always in touch! Your CopterHack team.

2021-11-08 14:15 UTC, okalachev approved these changes

2021-11-08 14:16 UTC, okalachev commented on docs/ru/сopter_сat.md
> +# Название проекта
Put project name here.

2021-11-29 13:54 UTC, matveylapin commented
# Software:

Сеть на ESP32 или на штатный Bluetooth:
* Возможность создания децентрализованной сети на коптерах:
  * Работа с любым коптером через подключение к одному:
    * Выполнение команд на одном или всех коптерах (например sudo reboot)
    * Рассылка файлов на коптеры (например файлов конфигурации или анимаций полета)
  * Отдельный канал для общения коптеров:
    * Бродкасты (например рассылка своей позиции в реальном времени чтобы не врезаться друг в друга) 
    * Отправка сообщений от одного коптера другому
* Что готово:
	* ESP32 подключена к RPi и взаимодействует с ROS
	* Написана прошивка, позволяющая отправлять и принимать сообщение по сети, а так же настройка самой сети (всё описанное происходит через rostopic)

# Hardware:
![CopterCat_cm4](https://user-images.githubusercontent.com/36163230/143879700-ae3badd1-d867-46e8-a4ce-80e144892010.png)
### Все компоненты подбирались опираясь на: 
  *  Наличие в продаже
  *  Год выпуска (логика была такая: более новые компоненты будут дольше производиться)
### Почему STM32F4?
  * При использовании внешней Flash памяти, этого микроконтроллера хватит на выполнение любых задач.
  * Более мощные модели дороже и их тяжелее найти. Нам кажется это золотая середина.
### Зачем 2 IMU?
  * BMI055 считается основным. Но на плате будут разведены места для обоих датчиков.
  * Если BMI055 пропадёт из продажи или не понравиться в работе, можно будет заменить его на MPU6500.
  *  В следующем апдейте MPU6500 будет перенесён на другие линии CS и DRDY.
### Почему type-c, но USB2.0?
  * Найти в наше тяжелое время PCIe на USB3.0 конвертор из-за дефицита чипов.
  * Если появится потребность в быстром USB, можно m.2 плату расширения.
### Питание: 
  * Планируется встроенный преобразователь 24v -> 5v 5A и разъём xt30 для питания платы. Подбираем преобразователь.
    * Логика питания:
		* При питании от USB PX4 лента и usb девайсы RPi запускаться не будут (чтобы не перегружать источник).
		* При питании от аккумулятора, плата работает в полноценном режиме.
		* Про питание от разъёма датчика тока, запускается только PX4.
### Что готово: 
* Выбраны датчики
* Выбран микроконтроллер
* Определили набор компонентов и портов
* Разработанно 3/4 схемы

# Мы сделали лого.
![котокоптер лого](https://user-images.githubusercontent.com/36163230/143879826-93638946-8265-4dc1-b272-2d0670683a76.png)

2022-04-18 05:07 UTC, merged