Copter-Hack - 2022 Scout_Drone.md
CopterExpress/clover pull request #421
Opened 2021-11-03 11:46 UTC by MustafaNatur

2021-11-03 14:24 UTC, okalachev requested changes
Please, fix this: https://github.com/CopterExpress/clover/runs/4092263363?check_suite_focus=true#step:5:4.

2021-11-03 14:24 UTC, okalachev commented on docs/ru/Scout_Drone.md
> +# Название проекта
Put your project or your team name here, please.

2021-11-03 14:24 UTC, okalachev commented on docs/ru/Scout_Drone.md
> +[CopterHack-2022](copterhack2022.md), команда Scout_Drone.
According to the template:

```suggestion
[CopterHack-2022](copterhack2022.md), команда **Scout_Drone**.
```

2021-11-03 14:24 UTC, okalachev commented on docs/ru/Scout_Drone.md
> +Mail: mustafa.natur@mail.ru;
Note, this all would be formatted as one line.

2021-11-03 14:24 UTC, okalachev commented on docs/ru/Scout_Drone.md
> +## Состав команды:
```suggestion
## Состав команды
```

2021-11-03 14:24 UTC, okalachev commented on docs/ru/Scout_Drone.md
> +## Описание проекта
```suggestion
## Описание проекта

```

2021-11-03 14:24 UTC, okalachev commented on docs/ru/Scout_Drone.md
> +Натур Мустафа Виссомович:
```suggestion
Натур Мустафа Виссомович:
```

2021-11-03 14:24 UTC, okalachev commented on docs/ru/Scout_Drone.md
> +Telegram: @Stuffy_Natur;
```suggestion
Telegram: @Stuffy_Natur;
```

2021-11-03 14:24 UTC, okalachev commented on docs/ru/Scout_Drone.md
> +Что должно получиться:
```suggestion
Что должно получиться:

```

2021-11-03 14:24 UTC, okalachev commented on docs/ru/Scout_Drone.md
> +6. Разаработка баззы данных для сбора информации (SQL, библиотека sqlite на языке Python)
```suggestion
1. Влагостойкий корпус.
2. Улучшенные аэродинамических характеристики за счет конструкторской разработки корпуса.
3. Защита силовой установки и других комплектующих за счет проектирования дополнительных деталей корпуса с использованием FDM печати, CAM станков (ЧПУ), заливки силикона в формы и т. д.
4. Возможность запланированных сценариев полета (телеметрия, GPS).
5. Возможность сбора информации за счет компьютерного зрения (работа с библиотекой OpenCV на языке Python).
6. Разработка базы данных для сбора информации (SQL, библиотека SQLite на языке Python),.
```

2021-11-03 14:24 UTC, okalachev commented on docs/ru/Scout_Drone.md
> +Я стал призером и победителем на таких конференциях, как Московский
Please, no line width limiting.

2021-11-03 14:24 UTC, okalachev commented on docs/ru/Scout_Drone.md
> +Клевер 4
More info required.

2021-11-03 15:46 UTC, okalachev commented
Also the article file name should not contain capital letters (since some file system are case insensitive and this may cause troubles).

2021-11-03 17:46 UTC, okalachev commented
Markdownlint tests still don't pass.

2021-11-03 18:03 UTC, MustafaNatur commented
I'm trying to solve the problem
--
Отправлено из Mail.ru для Android среда, 03 ноября 2021г., 20:46 +03:00 от Oleg Kalachev  ***@***.*** :

>Markdownlint tests still don't pass.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2021-11-03 19:02 UTC, MustafaNatur commented
I don't understand the problem. I've already fixed everything

>Среда, 3 ноября 2021, 17:25 +03:00 от Oleg Kalachev ***@***.***>:
> 
> 
***@***.*** requested changes on this pull request.
>Please, fix this:  https://github.com/CopterExpress/clover/runs/4092263363?check_suite_focus=true#step:5:4 .
>----------------------------------------------------------------------
>In  docs/ru/Scout_Drone.md :
>> @@ -0,0 +1,63 @@
>+# Название проекта
>
>Put your project or your team name here, please.
>----------------------------------------------------------------------
>In  docs/ru/Scout_Drone.md :
>> @@ -0,0 +1,63 @@
>+# Название проекта
>+
>+Создание поисково-спасательного беспилотного летательного аппарата
>+
>+[CopterHack-2022](copterhack2022.md), команда Scout_Drone.
>
>According to the template: ⬇️ Suggested change
>-[CopterHack-2022](copterhack2022.md), команда Scout_Drone.
>+[CopterHack-2022](copterhack2022.md), команда **Scout_Drone**.
>
>----------------------------------------------------------------------
>In  docs/ru/Scout_Drone.md :
>> @@ -0,0 +1,63 @@
>+# Название проекта
>+
>+Создание поисково-спасательного беспилотного летательного аппарата
>+
>+[CopterHack-2022](copterhack2022.md), команда Scout_Drone.
>+
>+## Состав команды:
>+
>+Натур Мустафа Виссомович: 
>+Mail: ***@***.***;
>
>Note, this all would be formatted as one line.
>----------------------------------------------------------------------
>In  docs/ru/Scout_Drone.md :
>> @@ -0,0 +1,63 @@
>+# Название проекта
>+
>+Создание поисково-спасательного беспилотного летательного аппарата
>+
>+[CopterHack-2022](copterhack2022.md), команда Scout_Drone.
>+
>+## Состав команды:
> ⬇️ Suggested change
>-## Состав команды:
>+## Состав команды
>
>----------------------------------------------------------------------
>In  docs/ru/Scout_Drone.md :
>> +Создание поисково-спасательного беспилотного летательного аппарата
>+
>+[CopterHack-2022](copterhack2022.md), команда Scout_Drone.
>+
>+## Состав команды:
>+
>+Натур Мустафа Виссомович: 
>+Mail: ***@***.***;
>+Telegram: @Stuffy_Natur; 
>+VK: https://vk.com/m.natur
>+GitHub: https://github.com/MustafaNatur
>+
>+* Натур Мустафа, @Stuffy_Natur, инженер.
>+* Натур Мустафа, @Stuffy_Natur, программист.
>+
>+## Описание проекта
> ⬇️ Suggested change
>-## Описание проекта
>+## Описание проекта
>
>----------------------------------------------------------------------
>In  docs/ru/Scout_Drone.md :
>> @@ -0,0 +1,63 @@
>+# Название проекта
>+
>+Создание поисково-спасательного беспилотного летательного аппарата
>+
>+[CopterHack-2022](copterhack2022.md), команда Scout_Drone.
>+
>+## Состав команды:
>+
>+Натур Мустафа Виссомович: 
> ⬇️ Suggested change
>-Натур Мустафа Виссомович: 
>+Натур Мустафа Виссомович:
>
>----------------------------------------------------------------------
>In  docs/ru/Scout_Drone.md :
>> @@ -0,0 +1,63 @@
>+# Название проекта
>+
>+Создание поисково-спасательного беспилотного летательного аппарата
>+
>+[CopterHack-2022](copterhack2022.md), команда Scout_Drone.
>+
>+## Состав команды:
>+
>+Натур Мустафа Виссомович: 
>+Mail: ***@***.***;
>+Telegram: @Stuffy_Natur; 
> ⬇️ Suggested change
>-Telegram: @Stuffy_Natur; 
>+Telegram: @Stuffy_Natur;
>
>----------------------------------------------------------------------
>In  docs/ru/Scout_Drone.md :
>> +Разработки БПЛА требуют продуманных конструкторских решений и ярких идей по увеличению возможностей и реализации характеристик автономности, поэтому актуально создавать надежных и многозадачных помощников.
>+
>+### Идея проекта
>+
>+Целью работы является конструкторская разработка и создание поисково-спасательного беспилотного летательного аппарата со слежущими оличительными особеностями и возможностями.
>+
>+1. Влагостойкий корпус
>+2. Улучшеные аэродинамических характеристики за счет конструкторской разработки корпуса
>+3. Защита силовой установки и других комплектующих за счет проектирования дополнительных деталей корпуса с использованием FDM печати, CAM станков (ЧПУ), заливки селикона в формы и тд.
>+4. Возможность запланированных сценариев полета (телеметрия, GPS)
>+5. Возможность сбора информации за счет компьютерного зрения (работа с библиоткеой OpneCV на языке Python)
>+6. Разаработка баззы данных для сбора информации (SQL, библиотека sqlite на языке Python)
>+
>+### Планируемые результаты
>+
>+Что должно получиться:
> ⬇️ Suggested change
>-Что должно получиться:
>+Что должно получиться:
>
>----------------------------------------------------------------------
>In  docs/ru/Scout_Drone.md :
>> +1. Влагостойкий корпус
>+2. Улучшеные аэродинамических характеристики за счет конструкторской разработки корпуса
>+3. Защита силовой установки и других комплектующих за счет проектирования дополнительных деталей корпуса с использованием FDM печати, CAM станков (ЧПУ), заливки селикона в формы и тд.
>+4. Возможность запланированных сценариев полета (телеметрия, GPS)
>+5. Возможность сбора информации за счет компьютерного зрения (работа с библиоткеой OpneCV на языке Python)
>+6. Разаработка баззы данных для сбора информации (SQL, библиотека sqlite на языке Python)
> ⬇️ Suggested change
>-1. Влагостойкий корпус
>-2. Улучшеные аэродинамических характеристики за счет конструкторской разработки корпуса
>-3. Защита силовой установки и других комплектующих за счет проектирования дополнительных деталей корпуса с использованием FDM печати, CAM станков (ЧПУ), заливки селикона в формы и тд.
>-4. Возможность запланированных сценариев полета (телеметрия, GPS)
>-5. Возможность сбора информации за счет компьютерного зрения (работа с библиоткеой OpneCV на языке Python)
>-6. Разаработка баззы данных для сбора информации (SQL, библиотека sqlite на языке Python)
>+1. Влагостойкий корпус.
>+2. Улучшенные аэродинамических характеристики за счет конструкторской разработки корпуса.
>+3. Защита силовой установки и других комплектующих за счет проектирования дополнительных деталей корпуса с использованием FDM печати, CAM станков (ЧПУ), заливки силикона в формы и т. д.
>+4. Возможность запланированных сценариев полета (телеметрия, GPS).
>+5. Возможность сбора информации за счет компьютерного зрения (работа с библиотекой OpenCV на языке Python).
>+6. Разработка базы данных для сбора информации (SQL, библиотека SQLite на языке Python),.
>
>----------------------------------------------------------------------
>In  docs/ru/Scout_Drone.md :
>> +### Планируемые результаты
>+
>+Что должно получиться:
>+Функциональный БПЛА с видеокамерой, включающий аэродинамический корпус с защитной функцией и необходимые конструктивы,
>+создана защита от разгерметизации корпуса БПЛА с помощью силиконовых прокладок. Созданный поисковоспасательный БПЛА способен
>+конкурировать с действующими аналогами, и при дальнейшем улучшении полетных характеристик вполне может использоваться подразделениями МЧС
>+и полиции. Реалезована возможность сбора фото и видео данных, возможность компьютерного зрения и распознования образов. Реализованна возможность полета дрона по заданным точкам
>+или по заданной траектории. Также планируется создание базы данных для сбора информации.
>+
>+### Использование платформы "Клевер"
>+
>+Клевер 4
>+
>+### Дополнительная информация по желанию участников
>+
>+Я стал призером и победителем на таких конференциях, как Московский 
>
>Please, no line width limiting.
>----------------------------------------------------------------------
>In  docs/ru/Scout_Drone.md :
>> +4. Возможность запланированных сценариев полета (телеметрия, GPS)
>+5. Возможность сбора информации за счет компьютерного зрения (работа с библиоткеой OpneCV на языке Python)
>+6. Разаработка баззы данных для сбора информации (SQL, библиотека sqlite на языке Python)
>+
>+### Планируемые результаты
>+
>+Что должно получиться:
>+Функциональный БПЛА с видеокамерой, включающий аэродинамический корпус с защитной функцией и необходимые конструктивы,
>+создана защита от разгерметизации корпуса БПЛА с помощью силиконовых прокладок. Созданный поисковоспасательный БПЛА способен
>+конкурир [...]

2021-11-03 19:30 UTC, okalachev commented
I've fixed this for you, check the editing commit.

Please, do not use e-mail to answer on GitHub as your comments get a lot of junk cites and become completely unreadable.

Answer directly on the PR page: https://github.com/CopterExpress/clover/pull/421.

2021-11-03 19:31 UTC, okalachev approved these changes

2021-11-04 08:23 UTC, SeliverstovaE commented
Dear friend,

Thank you for your interest in the CopterHack 2022 contest. Your application has successfully passed the experts’ review and was accepted for the second project stage of the competition, which will be held until February 28, 2022. This stage will be followed by monthly updates, lectures, and guidance from industry experts.

What's next?

1. Join the Telegram group with participants of the second project stage “[CopterHack 2022, participants chat](https://t.me/joinchat/1KIDu8p5FGhlYTBi )”.  
2. Every month, you're expected to prepare free-form reports on the progress of your project (update) in this draft pull request. In your report please indicate your progress, what tasks have been solved. You are encouraged to attach photos and videos that demonstrate the results of the work done within the month.
3. Send the link to the update to the participants chat in the Telegram group.

In response to the message, you will receive feedback from the competition jury.

There is no specific date for sending the report, so you can send the report between the beginning and the end of the month.

Monthly updates become mandatory from November 2021. But as soon as you are in the telegram group, you can already send updates and receive feedback from the jury.

We are interested in helping you to complete your project as much as possible by the final stage. We wish you success!

Always in touch! Your CopterHack team.

2022-04-25 07:28 UTC, closed without merging

2022-04-25 07:33 UTC, SeliverstovaE commented
Dear Scout_Drone team,
We are closing pull request for your project as you didn’t get to the final round of the competition. 

You are welcome to submit your article to the clover documentation as an clover platform-based project. In order to do this please create a new pull request or make a comment to the existing one.

We wish you success in implementing your project and invite you to the next events.