docs: Control pdd ~ Gitbook statya
CopterExpress/clover pull request #437
Opened 2022-03-15 00:17 UTC by b0tn3t000

2022-03-15 09:31 UTC, okalachev commented
Привет!

Это в рамках чего сделан проект?

Обратите внимание на проблемы с оформлением: https://github.com/CopterExpress/clover/runs/5546515245?check_suite_focus=true#step:6:4

2022-03-15 11:32 UTC, londrwus commented
> Привет!
> 
> Это в рамках чего сделан проект?
> 
> Обратите внимание на проблемы с оформлением: https://github.com/CopterExpress/clover/runs/5546515245?check_suite_focus=true#step:6:4

Привет. Данный проект как проектная деятельность в университете, не CopterHack.

2022-03-15 12:51 UTC, okalachev requested changes

2022-03-15 12:51 UTC, okalachev commented on docs/ru/control_poloci.md
> +# Контроль соблюдения ПДД на выделенной полосе с дроном
Для названий файлов используется английский язык (не транслит). Например, `lane_control.md`. То же самое для названий изображений.

2022-03-16 08:47 UTC, okalachev requested changes

2022-03-16 08:47 UTC, okalachev commented on docs/ru/lane_control.md
> +
Добавьте, пожалуйста, сюда строку с авторством и контактами, например, почта, Telegram или другие.

2022-03-16 09:36 UTC, londrwus commented on docs/ru/lane_control.md
> +
Добавил. Извиняюсь за такое кол-во поправок

2022-03-16 18:40 UTC, merged