Create hawkeye
CopterExpress/clover pull request #451
Opened 2022-08-17 18:41 UTC by itsmekartikgupta

2022-08-23 11:39 UTC, okalachev commented
Your article file name should end in `.md` to get checked.

2022-09-01 19:42 UTC, okalachev requested changes

2022-09-01 19:42 UTC, okalachev commented on docs/en/hawkeye
> +# Project name
You need to rename your file with .md extension.

2022-09-07 17:38 UTC, SeliverstovaE commented
Dear CopterHack applicant, 
 
Thank you for submitting your application for the CopterHack 2023 projects competition! We appreciate your interest in the contest, the time you invested into your application and the effort you put into it. 
 
We regret to say that your project can not be accepted in the current form.  
 
We encourage you to improve your application via adding more information regarding relevance of the project to the Clover platform application and prospective project outcomes.

2023-07-08 11:27 UTC, closed without merging